// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnbkivmfhycxbftgbarm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuYmtpdm1maHljeGJmdGdiYXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDQ2ODYsImV4cCI6MjA2OTI4MDY4Nn0.gpBuXm4VHH5Xu0w8mFZ7MqCzo60AOVir1snZjAdLl24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});